# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode8
xcode_sdk: iphonesimulator9.3
xcode_scheme:
- JAYSON iOS
