name: Checks

on: [push]

jobs:
  test:
    runs-on: macos-15
    steps:
      - uses: maxim-lobanov/setup-xcode@v1.1
        with:
          xcode-version: "16.2"
      - uses: actions/checkout@v2
      - name: Run test
        run: swift test
  swiftpm:
    runs-on: macos-15
    steps:
      - uses: maxim-lobanov/setup-xcode@v1.1
        with:
          xcode-version: "16.2"
      - uses: actions/checkout@v2
      - name: Build
        run: swift build -v
