name: Tests

on: [push]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: maxim-lobanov/setup-xcode@v1.1
        with:
          xcode-version: "12.3"
      - uses: actions/checkout@v2
      - name: Run test
        run: fastlane test
  cocoapods-lint:
    runs-on: macos-latest
    steps:
      - uses: maxim-lobanov/setup-xcode@v1.1
        with:
          xcode-version: "12.3"
      - uses: actions/checkout@v2
      - name: Lint Cocoapods
        run: pod lib lint --allow-warnings
  swiftpm:
    runs-on: macOS-latest
    steps:
      - uses: maxim-lobanov/setup-xcode@v1.1
        with:
          xcode-version: "12.3"
      - uses: actions/checkout@v2
      - name: Build
        run: swift build -v
